; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Clickless Mouse"
#define MyAppVersion "3.2"
#define MyAppPublisher "Garrett Anderson"
#define MyAppURL "https://github.com/gband85/ClicklessMouse"
#define MyAppExeName "ClicklessMouse.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E5F77259-EEAC-4F75-8D0B-A9315F55F57B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=LICENSE
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=Clickless_Mouse_installer_3.2
SolidCompression=yes
WizardStyle=modern dynamic
SetupIconFile=ClicklessMouse\clicklessmouse.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "publish\win-x64\app\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\av_libglesv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Base.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Controls.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.DesignerSupport.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Desktop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Dialogs.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Fonts.Inter.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.FreeDesktop.AtSpi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.FreeDesktop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.HarfBuzz.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Markup.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Markup.Xaml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Metal.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.MicroCom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Native.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.OpenGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Remote.Protocol.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Skia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Themes.Simple.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Vulkan.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Win32.Automation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.Win32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Avalonia.X11.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\AvaloniaEdit.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ClicklessMouse.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\clicklessmouse.desktop"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ClicklessMouse.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ClicklessMouse.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ClicklessMouse.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ClicklessMouse.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ColorDocument.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ColorTextBlock.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\defaults.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\DialogHost.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\DynamicData.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Egorozh.ColorPicker.Avalonia.Dialog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Egorozh.ColorPicker.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ExCSS.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\HarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\HtmlAgilityPack.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\libHarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\libHarfBuzzSharp.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\libSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\libSkiaSharp.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Markdown.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Markdown.Avalonia.Full.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Markdown.Avalonia.Html.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Markdown.Avalonia.Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Markdown.Avalonia.SyntaxHigh.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\MicroCom.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\MsBox.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ReactiveUI.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ReactiveUI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\ShimSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\SkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Splat.Builder.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Splat.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Splat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Splat.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Svg.Controls.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Svg.Custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Svg.Model.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Svg.SceneGraph.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\System.Reactive.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\Tmds.DBus.Protocol.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\WindowsInput.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\X11.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\win-x64\app\pl-PL\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "publish\win-x64\app\zh-Hans\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
;Registry data from file Run.reg
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; Flags: uninsdeletekey; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Clickless Mouse"; ValueData: "C:\Program Files\Clickless Mouse\ClicklessMouse.exe"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
;End of registry data from file Run.reg

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

