<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <UseWindowsForms>False</UseWindowsForms>
    <UseWPF>False</UseWPF>
    <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
    <ApplicationIcon>Assets\icons\clicklessmouse.ico</ApplicationIcon>
    <Description>Clickless Mouse is a Windows/Linux program which allows using the mouse without clicking. Forked from https://github.com/ProperCode/Clickless-Mouse</Description>
    <Copyright>Garrett Anderson</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Authors>Garrett Anderson</Authors>
    <PackageTags>mouse;accessibility;rsi;carpal-tunnel</PackageTags>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageReleaseNotes>https://github.com/gband85/$(AssemblyName)/blob/rebuild/changelog.md</PackageReleaseNotes>
    <PackageIcon>Assets\icons\clicklessmouse.png</PackageIcon>
    <PackageProjectUrl>https://github.com/gband85/$(AssemblyName)</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <Version>3.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)'=='true'">
    <DefineConstants>_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsLinux)'=='true'">
    <DefineConstants>_LINUX</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition
    below is needed to remove AvaloniaUI.DiagnosticsSupport package from build output in Release
    configuration.-->
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="InputSimulatorCore" />
    <PackageReference Include="Markdown.Avalonia" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="X11.Interop" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\1en.md" CopyToOutputDirectory="Always" />
    <AvaloniaResource Include="Assets\1pl.md" CopyToOutputDirectory="Always" />
    <AvaloniaResource Include="Assets\1en.jpg" CopyToOutputDirectory="Always" />
    <AvaloniaResource Include="Assets\1pl.jpg" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Assets\defaults.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>defaults.json</TargetPath>
    </None>
    <None Include="Assets\clicklessmouse.desktop">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>clicklessmouse.desktop</TargetPath>
    </None>
    
      <AvaloniaResource Include="Assets/icons/clicklessmouse.ico" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
  <Reference Include="Egorozh.ColorPicker">
    <HintPath>Lib\Egorozh.ColorPicker.Avalonia.dll</HintPath>
  </Reference>
    <Reference Include="Egorozh.ColorPicker.Dialog">
      <HintPath>Lib\Egorozh.ColorPicker.Avalonia.Dialog.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>