<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.0.4" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageVersion Include="Avalonia.Themes.Simple" Version="12.0.4" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.2" />
    <PackageVersion Include="InputSimulatorCore" Version="1.0.5" />
    <PackageVersion Include="Markdown.Avalonia" Version="12.0.0-a3" />
    <PackageVersion Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="12.0.3" />
    <PackageVersion Include="X11.Interop" Version="1.1.1" />
  </ItemGroup>
</Project>